// Code pour les imports : ------------------------------------------------------//
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Banner from "./components/Banner";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast"
import { Suspense } from "react"; 



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


// Code pour les métadatas: --------------------------------------------------------//
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};






// Code pour l'affichage du layout : -----------------------------------------------//
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
      <link href="https://fonts.googleapis.com/css2?family=Boogaloo&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet"/>
      </head>
      <Suspense fallback={<div>Loading...</div>}>
      <body>
        <Banner/>
        <Nav/>

          <Toaster position="top-right" reverseOrder={false} toastOptions = {{ className: "mt-2"}} />
          <main>{children}</main>

        <Footer/>

      </body>
      </Suspense>
    </html>
  );
}
